import { VoicePersonaInfo, VoiceTone, VoiceToneOption, GeminiVoiceName } from '../types';

export const VOICE_PERSONAS: VoicePersonaInfo[] = [
  {
    id: 'sarah',
    name: 'Prof. Sarah',
    voiceName: 'Kore',
    gender: 'female',
    role: 'Intuitive & Encouraging',
    avatar: '👩‍🏫',
    pitch: 1.05,
    rate: 0.95,
  },
  {
    id: 'alan',
    name: 'Dr. Alan',
    voiceName: 'Fenrir',
    gender: 'male',
    role: 'Rigorous & Formal',
    avatar: '👨‍🏫',
    pitch: 0.92,
    rate: 1.0,
  },
  {
    id: 'maya',
    name: 'Maya',
    voiceName: 'Zephyr',
    gender: 'female',
    role: 'Lively & Dynamic',
    avatar: '👩‍🔬',
    pitch: 1.12,
    rate: 1.05,
  },
  {
    id: 'alex',
    name: 'Alex',
    voiceName: 'Puck',
    gender: 'male',
    role: 'Study Buddy & Friendly',
    avatar: '🧑‍💻',
    pitch: 1.0,
    rate: 1.0,
  },
  {
    id: 'thorne',
    name: 'Master Thorne',
    voiceName: 'Charon',
    gender: 'male',
    role: 'Patient Master & Deliberate',
    avatar: '🧙‍♂️',
    pitch: 0.88,
    rate: 0.92,
  },
];

export const VOICE_TONES: VoiceToneOption[] = [
  {
    id: 'encouraging',
    label: 'Encouraging & Patient',
    description: 'Warm supportive cadence, praise for progress, and confidence building',
    badge: 'Warm & Uplifting',
    promptInstruction: 'Say in an encouraging, warm, and patient tutor tone with supportive cadence',
  },
  {
    id: 'analytical',
    label: 'Analytical & Rigorous',
    description: 'Methodical lecture, formal precision, and exact mathematical definitions',
    badge: 'Academic Rigor',
    promptInstruction: 'Say in a formal, precise, and analytical academic lecture tone',
  },
  {
    id: 'energetic',
    label: 'Energetic & Inspiring',
    description: 'High momentum, passionate delivery, and motivating enthusiasm',
    badge: 'High Energy',
    promptInstruction: 'Say in an upbeat, energetic, and passionate tone with vibrant momentum',
  },
  {
    id: 'socratic',
    label: 'Socratic & Inquisitive',
    description: 'Guiding rhetorical questions, thoughtful pauses, and conceptual discovery',
    badge: 'Inquisitive',
    promptInstruction: 'Say in a thoughtful, reflective, and inquisitive Socratic tone',
  },
  {
    id: 'calm',
    label: 'Calm & Reassuring',
    description: 'Measured tempo, soothing guidance, easing exam anxiety',
    badge: 'Exam Calm',
    promptInstruction: 'Say in a calm, soothing, and reassuring cadence',
  },
];

// Audio cache to prevent re-requesting the exact same text + voice + tone
const audioMemoryCache = new Map<string, string>();

export interface SpeechRequestOptions {
  text: string;
  voiceName: GeminiVoiceName;
  tone: VoiceTone;
}

export interface SpeechResult {
  success: boolean;
  audioUrl?: string;
  fallback?: boolean;
  cleanText?: string;
  isCached?: boolean;
}

/**
 * Fetch Realistic AI Speech generated by Gemini TTS on the server
 */
export async function fetchRealisticSpeech({
  text,
  voiceName,
  tone,
}: SpeechRequestOptions): Promise<SpeechResult> {
  const cacheKey = `${voiceName}:${tone}:${text.trim()}`;
  if (audioMemoryCache.has(cacheKey)) {
    return {
      success: true,
      audioUrl: audioMemoryCache.get(cacheKey)!,
      isCached: true,
    };
  }

  try {
    const res = await fetch('/api/generate-speech', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, voiceName, tone }),
    });

    if (!res.ok) {
      throw new Error(`Speech API response status ${res.status}`);
    }

    const data = await res.json();
    if (data.success && data.audioDataUrl) {
      audioMemoryCache.set(cacheKey, data.audioDataUrl);
      return {
        success: true,
        audioUrl: data.audioDataUrl,
        cleanText: data.cleanText,
      };
    }

    return {
      success: false,
      fallback: true,
      cleanText: data.cleanText || text,
    };
  } catch (err) {
    console.warn('Realistic AI voice request notice:', err);
    return {
      success: false,
      fallback: true,
      cleanText: text,
    };
  }
}
